### ISSUE TITLE
Can we update to a newer version of aws-java-sdk?

### ISSUE THREAD

**Issue by max-rocket-internet** [seahen/maven-s3-wagon#14]
Version `1.11.16` is very old and doesn't support the newer AWS authentication flows, such as `AssumeRoleWithWebIdentity`

**Comment by seahen** [comment]
I forgot what a pain publishing a release to maven central can be sometimes, but it is done: 1.3.2

**Comment by devendra-dh** [comment]
still need this [PR](https://github.com/seahen/maven-s3-wagon/pull/20)
